development:
  adapter:   mysql
  database:  TheCivicCommons_dev
  username:  civiccommons
  password:  
  host:      localhost



test:
  adapter:   mysql
  database:  TheCivicCommons_test
  username:  civiccommons
  password:  
  host:      localhost

